version: "3"
services:
  shop:
    build: ./shop
    ports:
      - "3010:3010"
    healthcheck:
      test: curl --fail -s http://localhost:3010/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  wharehouse:
    build: ./wharehouse
    ports:
      - "4000:4000"
    healthcheck:
      test: curl --fail -s http://localhost:4000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
